name: CI
on:
  push:
    branches:
      - '**'
      - '!dependabot/**'
  pull_request_target:
    # NOTE: does not work for some reasons
    # branches:
    #   - 'dependabot/**'

env:
  ORG_SECRET: ${{ secrets.ORG_SECRET }}

jobs:
  use_secrets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: 'Use secrets'
        run: |
          cat README.md
          test -n "$ORG_SECRET"
