name: CI
on:
  push:
    branches:
      - 'main'
  pull_request_target:

env:
  ORG_SECRET: ${{ secrets.ORG_SECRET }}
  MEMBERS_CAN_TRIGGER_CI: |
    cjavilla-stripe
    hibariya
    paulasjes-stripe
    hideokamoto-stripe

jobs:
  require-contributor:
    runs-on: ubuntu-latest
    steps:
      - name: 'check if the sender is one of the contributors'
        run: |
          echo "$MEMBERS_CAN_TRIGGER_CI"

          if [[ "$MEMBERS_CAN_TRIGGER_CI" =~ ^${{ github.event.sender.login }}$ ]]; then
            echo "can proceed"
            exit
          else
            echo "cannot proceed"
            exit 1
          fi

  use-secrets:
    needs: ['require-contributor']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: 'Use secrets'
        run: |
          cat README.md
          test -n "$ORG_SECRET"
