name: CI
on:
  push:
    branches:
      - 'main'
  pull_request_target:

env:
  ORG_SECRET: ${{ secrets.ORG_SECRET }}
  MEMBERS_CAN_TRIGGER_CI: |
    cjavilla-stripe
    hibariya
    paulasjes-stripe
    hideokamoto-stripe
    dependabot[bot]

jobs:
  require-permission:
    runs-on: ubuntu-latest
    steps:
      - name: 'check if the triggering actor is one of the contributors'
        run: |
          echo "$MEMBERS_CAN_TRIGGER_CI"

          while read item; do
            if [[ "$item" == "${{ github.triggering_actor }}" ]]; then
              exit # has permission
            fi
          done <<< "$MEMBERS_CAN_TRIGGER_CI"

          echo 'CI have to be re-run by one of the $MEMBERS_CAN_TRIGGER_CI' >> $GITHUB_STEP_SUMMARY
          exit 1

  use-secrets:
    needs: ['require-permission']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.after || github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: 'Use secrets'
        run: |
          echo "${{ github.event.after }}"
          echo "${{ github.event.pull_request.head.sha }}"
          cat .github/workflows/ci.yml
          cat README.md
          test -n "$ORG_SECRET"

